use test;

-- dirdy read
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM Users WHERE name = 'Bob';
-- 결과: 27 (업데이트된 값(40)이 보이지 않음) -- Dirty Read 방지
COMMIT;

-- non repeatable 
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
UPDATE Users SET age = 32 WHERE name = 'Bob';
COMMIT;

-- 팬텀 리드
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
INSERT INTO Users VALUES (3, 'Charlie', 29);
COMMIT;
